### ISSUE TITLE
Prop validator with regular function (not arrow) breaks props inference in setup

### ISSUE THREAD

**Issue by dodas** [vuejs/composition-api#152]
version: v0.3.2

```ts
createComponent({
  props: {
    someProp: {
      type: String,
      // using arrow function
      validator: () => true
    }
  },
  setup(props)
    // this is ok, props has correct type
  }
})
```

```ts
createComponent({
  props: {
    someProp: {
      type: String,
      // using regular function or shorthand method name
      // validator() {
      validator: function() {
        return true
      }
    },
  },
  setup(props) {
    // props is any
  }
})
```

Edit: Also, expecting argument in validator breaks type inference:

```ts
createComponent({
  props: {
    someProp: {
      type: String,
      validator: (val) => true,
    },
  },
  setup(props) {
    // props is any
  }
})
```

**Comment by liximomo** [comment]
Seems like a TypeScript bug, can't find a workaround now.

**Comment by rickyruiz** [comment]
In componentProps.d.ts

```ts
export interface PropOptions<T = any, Required extends boolean = false> {
    type?: PropType<T> | null;
    required?: Required;
    default?: T | null | undefined | (() => T | null | undefined);
    validator?(value: any): boolean;
}
```

Replacing `validator?(value: any): boolean;` with `validator?(value: T): boolean;` should fix the argument issue.

**Comment by iulo** [comment]
@rickyruiz Hi bro, anyway fix this without change original composition-api d.ts? like Omit it in local project? Im a new ts user and this issue make me irritable

**Comment by rickyruiz** [comment]
@iulo A workaround is to explicitly type the `value` argument of the validator function:

```ts
import { defineComponent, PropType } from '@vue/composition-api'

type SomeType= 'foo' | 'bar'

defineComponent({
  props: {
    someProp: {
      type: String as PropType<SomeType>,
      default: 'foo',
      validator: (value: SometType) => true,
    },
  },
  setup({ val }) {
    // val is SomeType
  }
})
```

**Comment by iulo** [comment]
@rickyruiz  still no luck. typescript version 3.8.3. Got props any

![image](https://user-images.githubusercontent.com/6769037/76684688-fdcd7380-6648-11ea-8a5f-5afab8a15913.png)

**Comment by rickyruiz** [comment]
@iulo Do `validator: (val) => {}` instead of `validator(val) {}`

<img width="676" alt="Screen Shot 2020-03-15 at 11 42 16 PM" src="https://user-images.githubusercontent.com/12017329/76729554-a269b700-6716-11ea-94b7-3c3bfa45e87f.png">

<img width="676" alt="Screen Shot 2020-03-15 at 11 42 44 PM" src="https://user-images.githubusercontent.com/12017329/76729590-b31a2d00-6716-11ea-9ba9-eb34ab06704e.png">

**Comment by iulo** [comment]
@rickyruiz It work! Thanks man.
